"""Initial schema ESSA Store

Revision ID: c9b50081130a
Revises: 
Create Date: 2026-05-11 10:17:40.298244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b50081130a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_session', sa.String(), nullable=True),
    sa.Column('before_json', sa.String(), nullable=True),
    sa.Column('after_json', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_record_id'), 'audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_table('modal_operasional',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('jenis', sa.String(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('person_type', sa.String(), nullable=False),
    sa.Column('nama_uppercase', sa.String(), sa.Computed('UPPER(nama)', ), nullable=True),
    sa.Column('no_hp', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_nama_uppercase'), 'persons', ['nama_uppercase'], unique=False)
    op.create_index(op.f('ix_persons_person_type'), 'persons', ['person_type'], unique=False)
    op.create_table('sku_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode_sku', sa.String(), nullable=False),
    sa.Column('nama_produk', sa.String(), nullable=False),
    sa.Column('parent_sku_id', sa.Integer(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('warna', sa.String(), nullable=True),
    sa.Column('ukuran', sa.String(), nullable=True),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('harga_jual', sa.Float(), nullable=False),
    sa.Column('harga_modal', sa.Float(), nullable=False),
    sa.Column('kain_cost', sa.Float(), nullable=False),
    sa.Column('potongan_cost', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_master_kode_sku'), 'sku_master', ['kode_sku'], unique=True)
    op.create_index(op.f('ix_sku_master_model'), 'sku_master', ['model'], unique=False)
    op.create_index(op.f('ix_sku_master_parent_sku_id'), 'sku_master', ['parent_sku_id'], unique=False)
    op.create_table('bon_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('bon_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('sumber', sa.String(), nullable=False),
    sa.Column('sumber_ref_id', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bon_movements_person_id'), 'bon_movements', ['person_id'], unique=False)
    op.create_table('debt_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipe_hutang', sa.String(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('nominal_hutang', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_entries_person_id'), 'debt_entries', ['person_id'], unique=False)
    op.create_index(op.f('ix_debt_entries_status'), 'debt_entries', ['status'], unique=False)
    op.create_index(op.f('ix_debt_entries_tipe_hutang'), 'debt_entries', ['tipe_hutang'], unique=False)
    op.create_table('distribusi_cutting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribusi_cutting_person_id'), 'distribusi_cutting', ['person_id'], unique=False)
    op.create_table('garapan_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('model_code', sa.String(), nullable=True),
    sa.Column('tarif_per_pcs', sa.Float(), nullable=False),
    sa.Column('berlaku_sejak', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garapan_rates_model_code'), 'garapan_rates', ['model_code'], unique=False)
    op.create_table('hasil_cutting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_invoice', sa.String(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('diskon', sa.Float(), nullable=False),
    sa.Column('ongkir', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('dp', sa.Float(), nullable=False),
    sa.Column('sisa', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_invoice')
    )
    op.create_index(op.f('ix_invoices_person_id'), 'invoices', ['person_id'], unique=False)
    op.create_table('pengeluaran_offline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('periode_mulai', sa.String(), nullable=True),
    sa.Column('periode_akhir', sa.String(), nullable=True),
    sa.Column('tanggal_proses', sa.String(), nullable=False),
    sa.Column('gaji_kotor', sa.Float(), nullable=False),
    sa.Column('bon_lama', sa.Float(), nullable=False),
    sa.Column('tambah_bon', sa.Float(), nullable=False),
    sa.Column('potong_bon', sa.Float(), nullable=False),
    sa.Column('gaji_bersih', sa.Float(), nullable=False),
    sa.Column('sisa_bon_akhir', sa.Float(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('excel_path', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_runs_person_id'), 'salary_runs', ['person_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('sumber_ref', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_sku_id'), 'stock_movements', ['sku_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salary_run_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=False),
    sa.Column('tap_masuk', sa.String(), nullable=True),
    sa.Column('tap_keluar', sa.String(), nullable=True),
    sa.Column('total_menit', sa.Integer(), nullable=False),
    sa.Column('menit_normal', sa.Integer(), nullable=False),
    sa.Column('menit_lembur', sa.Integer(), nullable=False),
    sa.Column('tarif_normal', sa.Float(), nullable=False),
    sa.Column('tarif_lembur', sa.Float(), nullable=False),
    sa.Column('pendapatan', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['salary_run_id'], ['salary_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_person_id'), 'attendance_records', ['person_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_salary_run_id'), 'attendance_records', ['salary_run_id'], unique=False)
    op.create_table('client_receivables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('sisa', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_receivables_person_id'), 'client_receivables', ['person_id'], unique=False)
    op.create_table('debt_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debt_entry_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_bayar', sa.String(), nullable=False),
    sa.Column('nominal_bayar', sa.Float(), nullable=False),
    sa.Column('metode', sa.String(), nullable=True),
    sa.Column('bon_used', sa.Float(), nullable=False),
    sa.Column('nota_pdf_path', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['debt_entry_id'], ['debt_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_payments_debt_entry_id'), 'debt_payments', ['debt_entry_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Float(), nullable=False),
    sa.Column('diskon_line', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengsup_reconciliation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salary_run_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('harga_per_unit', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['salary_run_id'], ['salary_runs.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salary_run_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('model_code', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('tarif_per_pcs', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['salary_run_id'], ['salary_runs.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_receivable_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receivable_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_bayar', sa.String(), nullable=False),
    sa.Column('nominal_bayar', sa.Float(), nullable=False),
    sa.Column('metode', sa.String(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receivable_id'], ['client_receivables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_receivable_payments')
    op.drop_table('salary_line_items')
    op.drop_table('pengsup_reconciliation')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_debt_payments_debt_entry_id'), table_name='debt_payments')
    op.drop_table('debt_payments')
    op.drop_index(op.f('ix_client_receivables_person_id'), table_name='client_receivables')
    op.drop_table('client_receivables')
    op.drop_index(op.f('ix_attendance_records_salary_run_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_person_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_stock_movements_sku_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_salary_runs_person_id'), table_name='salary_runs')
    op.drop_table('salary_runs')
    op.drop_table('pengeluaran_offline')
    op.drop_index(op.f('ix_invoices_person_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('hasil_cutting')
    op.drop_index(op.f('ix_garapan_rates_model_code'), table_name='garapan_rates')
    op.drop_table('garapan_rates')
    op.drop_index(op.f('ix_distribusi_cutting_person_id'), table_name='distribusi_cutting')
    op.drop_table('distribusi_cutting')
    op.drop_index(op.f('ix_debt_entries_tipe_hutang'), table_name='debt_entries')
    op.drop_index(op.f('ix_debt_entries_status'), table_name='debt_entries')
    op.drop_index(op.f('ix_debt_entries_person_id'), table_name='debt_entries')
    op.drop_table('debt_entries')
    op.drop_index(op.f('ix_bon_movements_person_id'), table_name='bon_movements')
    op.drop_table('bon_movements')
    op.drop_table('bon_balances')
    op.drop_index(op.f('ix_sku_master_parent_sku_id'), table_name='sku_master')
    op.drop_index(op.f('ix_sku_master_model'), table_name='sku_master')
    op.drop_index(op.f('ix_sku_master_kode_sku'), table_name='sku_master')
    op.drop_table('sku_master')
    op.drop_index(op.f('ix_persons_person_type'), table_name='persons')
    op.drop_index(op.f('ix_persons_nama_uppercase'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('modal_operasional')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_record_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
